version: '3.8'
services:
  mongodb-primary:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_primary_data:/data/db

  mongodb-secondary:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - mongodb_secondary_data:/data/db

volumes:
  mongodb_primary_data:
  mongodb_secondary_data: