services:
  mongodb-primary:
    image: mongo
    container_name: mongodb-primary
    ports:
      - "27018:27017"
    command: --replSet rs0
    volumes:
      - mongodb_primary_data:/data/db
  mongodb-secondary:
    image: mongo
    container_name: mongodb-secondary
    ports:
      - "27019:27017"
    command: --replSet rs0
    volumes:
      - mongodb_secondary_data:/data/db

volumes:
  mongodb_primary_data:
  mongodb_secondary_data:
